# Generated by Django 4.2.1 on 2023-05-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
